chat/urls.py
from django.urls import path
 
from . import views

app_name = 'chat' 

urlpatterns = [
    # path('', views.index, name='index')
    path('room/', views.selectRoom, name='select-room'),   # 房间选择
    path('<str:room_name>/', views.room, name='room'),
    path('login/',views.log_in,name='login'),
    path('logon/',views.logon,name='logon'),
    path('logout/', views.logout, name='logout'),
    path('reset/', views.logout, name='reset'),
    path('main/', views.main, name='main')

]

chatroom/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path, include
from chat.views import index
from chat.views import log_in, logon, logout, index

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),

    # path('room/',index,name='index'),
    path('',log_in,name='login'),
    path('login/',log_in,name='login'),
    path('logon/',logon,name='logon'),
    path('logout/', logout, name='logout'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/mysite/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

demo/mysite/mysite/urls.py
# mysite/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=50)
    # members = models.ManyToManyField(Account, blank=True)

    def __str__(self):
        return self.name
    

class Account(models.Model):
    username=models.CharField(max_length=20)
    password=models.CharField(max_length=200)
    # id = models.AutoField(primary_key=True)
    # last_login = models.DateTimeField(auto_now_add=True)
    login = models.IntegerField(default=0)  # 0未登录，1登录
    friend = models.ManyToManyField('self', blank=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.username
    

demo/mysite/chat/models.py
from django.db import models

# Create your models here.

chat/forms.py
from django import forms
from .models import Account

class AccountLoginForm(forms.ModelForm):
    class Meta:
        model = Account

        fields = ('username', 'password') # , 'login'

class AccountLogonForm(forms.ModelForm):
    # password = forms.CharField()
    password2 = forms.CharField()
    
    class Meta:
        model = Account

        fields = ('username', 'password', 'password2')

    # 对两次输入的密码是否一致进行检查
    # def clean_password2(self):
    #     data = self.cleaned_data
    #     if data.get('password') == data.get('password2'):
    #         return data.get('password')
    #     else:
    #         raise forms.ValidationError("密码输入不一致,请重试。")
        
class AccountLogonForm(forms.ModelForm):
    # password = forms.CharField()
    password2 = forms.CharField()
    
    class Meta:
        model = Account

        fields = ('username', 'password', 'password2')

chat/views.py
from django.shortcuts import render, HttpResponse, redirect

from django.contrib.auth import authenticate, login

from .models import Account
from .forms import AccountLoginForm, AccountLogonForm

from django.contrib.auth.hashers import make_password
from django.db.models import Q
import hashlib


 
def index(request):
    return render(request, "chat/selectRoom.html")  # choose room
    # return render(request, "chat/login.html")

def room(request, room_name):
        return render(request, 'chat/room.html', {'room_name': room_name})

def selectRoom(request):
    if request.method == "POST":

    elif request.method == "GET":
        context = {'folder_form': folder_form}
        return render(request, 'chat/selectRoom.html')
    else:
        error_message = "非GET, POST请求!"
        return render(request, "error/printError.html", {'error_message': error_message})


def main(request):
    return render(request, 'chat/main.html')


def log_in(request):
    # return HttpResponse('登录成功')
    if request.method == 'POST':
        user_login_form = AccountLoginForm(request.POST)
        user_login_form.login = 0

        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            username = user_login_form.cleaned_data['username']
            password = user_login_form.cleaned_data['password']
            # hashed_password = make_password(password, salt=None, hasher='default')
            Encry = hashlib.md5()  # 实例化md5
            Encry.update(password.encode())  # 字符串字节加密
            hashed_password = Encry.hexdigest()

            user = user_login_form.save(commit=False)
            user.username = username
            user.password = hashed_password
            # user.save()

            # usernames = Account.objects.values('username')
            # account = Account.objects.get(username=username).first()
            try:
                matching_accounts = Account.objects.filter(username=username)
                # 找到账户，执行相应的操作
            except Account.DoesNotExist:
                error_message = "用户名不存在，请注册！"
                return render(request, "error/notLoginError.html", {'error_message': error_message})
            
            for account in matching_accounts:
                if account.password == user.password:
                    # user.login = 1
                    user.save()

                    return redirect("chat:main")

                else:
                    # error_message = user.password
                    error_message = "密码错误，请重新输入！"
                    return render(request, "error/notLoginError.html", {'error_message': error_message})

            # 用户验证
            # authenticated_user = authenticate(username=username, password=password)

            # if authenticated_user is not None:
            #     # 验证通过，执行登录
            #     login(request, user)
            #     return redirect("chat:room")

        else:
            error_message = "帐号密码错误，请重新输入~"
            return render(request, "error/notLoginError.html", {'error_message': error_message})
    
    elif request.method == 'GET':
        user_login_form = AccountLoginForm()
        context = {'form': user_login_form}
        return render(request, 'chat/login.html', context)
    else:
        # return HttpResponse("请使用GET或POST请求数据")
        error_message = "请使用GET或POST请求数据"
        return render(request, "error/notLoginError.html", {'error_message': error_message})

    
def checkLogin(request, account):
    if account.login != 1:
        error_message = "未登录！"
        return render(request, "error/notLoginError.html", {'error_message': error_message})
    else:
        return True
    

def logon(request):
    # return HttpResponse('注册页面')
    if request.method == 'POST':
        user_register_form = AccountLogonForm(request.POST)

        if user_register_form.is_valid():
            username = user_register_form.cleaned_data['username']
            password = user_register_form.cleaned_data['password']
            password2 = user_register_form.cleaned_data['password2']

            if password != password2:
                error_message = "密码输入不一致,请重试！"
                return render(request, "error/notLoginError.html", {'error_message': error_message})

            # hashed_password = make_password(password, salt=None, hasher='default')
            Encry = hashlib.md5()  # 实例化md5
            Encry.update(password.encode())  # 字符串字节加密
            hashed_password = Encry.hexdigest()

            user = user_register_form.save(commit=False)
            user.username = username
            user.password = hashed_password
            # user.login = 0

            if username is None:
                error_message = "用户名不存在"
                return render(request, "error/notLoginError.html", {'error_message': error_message})


            # account = Account.objects.get(username=user.username).first()
            try:
                account = Account.objects.get(username=user.username)
                # 找到账户，执行相应的操作
            except Account.DoesNotExist:
                user.save()
                return redirect("chat:login")

            # if account:
            error_message = "用户名已存在，请重新注册！"
            return render(request, "error/notLoginError.html", {'error_message': error_message})

            # else:
        else:
            error_message = "注册输入有误。请重新输入~"
            return render(request, "error/notLoginError.html", {'error_message': error_message})

    elif request.method == 'GET':
        user_register_form = AccountLogonForm()
        context = { 'form': user_register_form }
        return render(request, 'chat/register.html', context)
    else:
        error_message = "请使用GET或POST请求数据"
        return render(request, "error/notLoginError.html", {'error_message': error_message})


def logout(request):
    return HttpResponse('退出')

# def index(request):
#     return HttpResponse('主页面')

def error(request):
    return render(request, 'error/printError.html')

demo/mysite/chat/views.py
# chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'chat/index.html', {})

def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name
    })

templates/chat/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Chat Rooms</title>
</head>

<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function (e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>

</html>

templates/chat/login.html
{% load static %}



{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static 'bootstrap/css/bootstrap.css' %} >
    <title>登录</title>
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2 class="text-center mb-4">用户登录</h2>
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group">
                        <label for="username">账号</label>
                        <input type="text" class="form-control" id="username" name="username"value="{{ user.username }}">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password" value="{{ user.password }}">
                    </div>
                    <div class="form-group">
                        {{ form.captcha.label_tag }}
                        {{ form.captcha }}
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary btn-block">登录</button>
                    <div class="col-12">
                        <br>
                        <h5>还没有账号？</h5>
                        <h5>点击 <a href='{% url "logon" %}'>注册账号</a> 加入我们吧！</h5>
                        <h5>忘记密码了？</h5>
                        <h5>点击 <a href='{% url "chat:reset" %}'>这里</a>重置密码</h5>
                    </div>                    
                    </div>
                </form>
            </div>
        </div>
    </div>
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>#}
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>#}
{##}


<script src="{% static 'jquery/jquery_3.4.1_jquery.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
{#        <!-- <script src="{% static 'popper/1.15.0_umd_popper.js' %}"></script> -->#}

        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>
{% endblock content %}

templates/chat/logon.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title> 注册 </title>
		<link rel="stylesheet" href="/static/css/reset.css" />
		<link rel="stylesheet" href="/static/css/common.css" />
	</head>

	<body>
		<div class="wrap login_wrap">
			<div class="content">

				<div class="logo"></div>

				<div class="login_box">

					<div class="login_form">
						<div class="login_title">
							注册
						</div>
						<form action="{% url 'logon'%}" method="post">

							<div class="form_text_ipt">
								<input name="username" type="text" placeholder="手机号/邮箱">
							</div>
							<div class="ececk_warning"><span>数据不能为空</span></div>
							<div class="form_text_ipt">
								<input name="password" type="password" placeholder="密码">
							</div>
							<div class="ececk_warning"><span>数据不能为空</span></div>
							<div class="form_text_ipt">
								<input name="repassword" type="password" placeholder="重复密码">
							</div>
							<div class="ececk_warning"><span>数据不能为空</span></div>
							<div class="form_text_ipt">
								<input name="name" type="text" placeholder="验证码">
							</div>
							<div class="ececk_warning"><span>数据不能为空</span></div>

							<div class="form_btn">
								<button type="submit">注册</button>
							</div>
							<div class="form_reg_btn">
								<span>已有帐号？</span><a href="log_in.html">马上登录</a>
							</div>
						</form>
						<div class="other_login">
							<div class="left other_left">
								<span>其它登录方式</span>
							</div>
							<div class="right other_right">
								<a href="#">QQ登录</a>
								<a href="#">微信登录</a>
								<a href="#">微博登录</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript" src="/static/js/jquery.min.js" ></script>
		<script type="text/javascript" src="/static/js/common.js" ></script>
	</body>
</html>

templates/chat/main.html
{% extends "base.html" %}
{% load static %}

{% block title %}
首页
{% endblock title %}

{% block content %}
<div class="container mt-2">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3 mb-4" >
                <div class="form-group">
                    <div class="py-4 text-center align-self-center" style="font-size: 20px;">
                        <strong>主页面</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock content %}

templates/chat/register.html
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href={% static 'bootstrap/css/bootstrap.css' %}>
    <title>用户注册</title>
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2 class="text-center mb-4">用户注册</h2>
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- 昵称 -->
                    <div class="form-group">
                        <label for="username">昵称</label>
                        <input type="text" class="form-control" id="username" name="username" required value="{{ user.username }}">
                    </div>
                    <!-- 邮箱 -->
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">设置密码</label>
                        <input type="password" class="form-control" id="password" name="password" required value="{{ user.password }}">
                    </div>
                    <!-- 确认密码 -->
                    <div class="form-group">
                        <label for="password2">确认密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required value="{{ user.password2 }}">
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary btn-block">提交</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
{% endblock content %}

templates/chat/room.html
{% extends "base.html" %}
{% load static %}

{% block title %}
首页
{% endblock title %}

{% block content %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static 'bootstrap/css/bootstrap.css' %}>
    <title>Chat Room</title>
</head>

<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <!-- <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send"> -->

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3 mb-4" >
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="chat-message-input" name="chat-message-input" required>
                    <button type="submit" class="btn btn-primary btn-block mb-3" id="chat-message-submit" value="Send">发送</button>
                </div>
            </div>
        </div>
    </div>

    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>

</html>
{% endblock content %}

templates/chat/selectRoom.html
{% extends "base.html" %}
{% load static %}

{% block title %}
首页
{% endblock title %}

{% block content %}
<div class="container mt-2">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3 mb-4" >
                <div class="form-group">
                    <div class="py-4 text-center align-self-center" style="font-size: 20px;">
                        <strong>请输入群名</strong>
                    </div>
                    <input type="text" class="form-control mb-3" id="room-name-input" name="room-name-input" required>
                    <!-- <input id="chat-message-input" type="text" size="100"> -->
                    <button type="submit" class="btn btn-primary btn-block mb-3" id="room-name-submit" value="Send">进入</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function (e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };

        // .text-large {
        //     font-size: 20px;
        // }
    </script>

</div>


{% endblock content %}